// subscriptionController.js

import stripe from '../../config/stripe.js';
import User from '../../models/auth/User.js'; 
import mongoose from 'mongoose'; // ✅ ADDED: Import Mongoose for ObjectId handling
// NOTE: You'll also need to import verifyPaypalOrder from your paypal.client.js 
// if you choose to implement the full PayPal verification.

// =========================================================================
// 1. EXISTING FUNCTION: createCheckoutSession (For redirect flow)
// =========================================================================
export const createCheckoutSession = async (req, res) => {
    const { priceId } = req.body;
    const handymanId = req.user.id;
    
    try {
        // ✅ FIX 1: Explicitly cast the string ID to an ObjectId
        const objectId = new mongoose.Types.ObjectId(handymanId);
        const handyman = await User.findById(objectId);

        if (!handyman) {
            console.error(`User not found for ID: ${handymanId}`);
            return res.status(404).json({error: 'Authenticated user record not found.'});
        }
        
        let customerId = handyman.stripeCustomerId;

        if (!customerId) {
            const customer = await stripe.customers.create({ email: handyman.email });
            customerId = customer.id;
            // Update MongoDB with the new Customer ID
            await User.updateOne({ _id: handymanId }, { stripeCustomerId: customerId }); 
        }

        const session = await stripe.checkout.sessions.create({
            mode: 'subscription',
            customer: customerId,
            line_items: [{ price: priceId, quantity: 1 }],
            metadata: { handymanId: handymanId.toString() }, 
            success_url: `${process.env.CLIENT_URL}/subscription/success?session_id={CHECKOUT_SESSION_ID}`,
            cancel_url: `${process.env.CLIENT_URL}/subscription/cancel`,
        });

        res.status(200).json({ url: session.url });
    } catch (error) {
        console.error('Error creating checkout session:', error);
        res.status(500).json({ error: 'Failed to initiate payment process.' });
    }
};


// =========================================================================
// 2. NEW FUNCTION: createInlineSubscription (For Stripe Elements flow)
// =========================================================================
/**
 * Creates a Stripe Subscription directly using PaymentMethod ID 
 * received from the Stripe Elements form (inline payment).
 */
export const createInlineSubscription = async (req, res) => {
    // Requires: priceId and the paymentMethodId generated by the frontend
    const { priceId, paymentMethodId } = req.body;
    
    // We get the user ID from the authentication middleware (req.user.id)
    const handymanId = req.user.id; 

    if (!priceId || !paymentMethodId) {
        return res.status(400).json({ error: 'Missing priceId or paymentMethodId.' });
    }

    try {
        // ✅ FIX 2: Explicitly cast the string ID to an ObjectId
        const objectId = new mongoose.Types.ObjectId(handymanId);
        const handyman = await User.findById(objectId);
        
        if (!handyman) {
             return res.status(404).json({ error: 'Authenticated user record not found.' });
        }
        
        let customerId = handyman.stripeCustomerId;

        // 1. Find or Create Stripe Customer
        if (!customerId) {
            // Case 1: NEW Customer - Stripe handles attachment and default setting automatically
            const customer = await stripe.customers.create({ 
                email: handyman.email,
                payment_method: paymentMethodId,
                invoice_settings: { default_payment_method: paymentMethodId },
            });
            customerId = customer.id;
            // Update MongoDB with the new Customer ID
            await User.updateOne({ _id: handymanId }, { stripeCustomerId: customerId }); 
        } else {
             // Case 2: EXISTING Customer 
             
             // 🚨 FIX APPLIED: Explicitly ATTACH the payment method first
             await stripe.paymentMethods.attach(
                 paymentMethodId,
                 { customer: customerId }
             );

             // Then, update the customer's settings to use the attached payment method
             await stripe.customers.update(customerId, {
                 invoice_settings: { default_payment_method: paymentMethodId },
             });
        }
        
        // 2. Create the Subscription
        const subscription = await stripe.subscriptions.create({
            customer: customerId,
            items: [{ price: priceId }],
            // Ensures the subscription uses the attached card immediately
            collection_method: 'charge_automatically', 
            expand: ['latest_invoice.payment_intent'], 
        });

        // 3. SUCCESS: Send back the subscription data 
        res.status(200).json({
            message: "Subscription successfully initiated.",
            subscription: {
                id: subscription.id,
                status: subscription.status,
            }
        });

    } catch (error) {
        console.error("Error creating inline subscription:", error);
        // Send the specific error message from Stripe back to the frontend
        const errorMessage = error.raw ? error.raw.message : "Failed to process payment with provided card details.";
        res.status(500).json({ 
            error: errorMessage
        });
    }
};


// =========================================================================
// 3. NEW FUNCTION: confirmPayPalSubscription (For PayPal Orders flow)
// =========================================================================
export const confirmPayPalSubscription = async (req, res) => {
    
    const { orderId, planName } = req.body;
    const handymanId = req.user.id; 

    if (!orderId) {
         return res.status(400).json({ error: 'Missing PayPal Order ID.' });
    }

    try {
        // ✅ FIX 3: Explicitly cast the string ID to an ObjectId
        const objectId = new mongoose.Types.ObjectId(handymanId);
        const handyman = await User.findById(objectId);
        
        if (!handyman) {
             return res.status(404).json({ error: 'Authenticated user record not found.' });
        }
        
        console.log(`Received PayPal Order ID ${orderId} for user ${handymanId} on ${planName} plan.`);

        // 🚨 CRITICAL TODO: 
        // 1. IMPORT `verifyPaypalOrder` from your paypal.client.js
        // 2. CALL `const orderDetails = await verifyPaypalOrder(orderId);`
        // 3. CHECK `if (orderDetails.status !== 'COMPLETED')` and return error if needed.
        
        // Placeholder: Update user status in MongoDB here.
        // if (handyman) {
        //    await User.updateOne({ _id: handymanId }, { subscriptionStatus: 'active', paymentMethod: 'PayPal', subscriptionPlan: planName });
        // }
        
        return res.status(200).json({ 
            message: "PayPal subscription process confirmed on backend.",
            orderId: orderId
        });

    } catch (error) {
        console.error("PayPal backend confirmation failed:", error);
        res.status(500).json({ error: 'Failed to process PayPal confirmation.' });
    }
};